### ISSUE TITLE
Suggestions for Improvements

### ISSUE THREAD

**Issue by divyanshu013** [parasjain95/team-member-management#1]
Hi @parasjain95, went through the code. It looks good overall 👍 

Here are a few suggestions I had from my end:

1. The `AddMember` and `EditMember` components can share some logic and presentational layer.
2. They are currently using refs to access input values. Would have preffered if it was using state instead of refs.
3. The dataflow could have been made modular by separating out actions, currently it's coupled in the components.

Please let me know if you have any doubts. Happy to help 🙂

**Comment by parasjain95** [comment]
Hi,
I have made the changes as per your suggestions.
I hope I addressed everything as expected.

Thanks
